version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
    - postgres:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    ports:
      - 5000:5000
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev:migrate" 
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

volumes:
  postgres: