version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  node:
    container_name: node
    build: .
    ports:
      - 5000:5000
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run test" 
    depends_on:
      - db
    env_file:
      - .env.test